version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/data/mysite.local
      - phpsocket:/var/run
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./public:/data/mysite.local
      - phpsocket:/var/run
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  phpsocket: